INSERT INTO genres (name) VALUES 
('Action'),
('Adventure'),
('Avant Garde'),
('Award Winning'),
('Boys Love'),
('Comedy'),
('Drama'),
('Ecchi'),
('Erotica'),
('Fantasy'),
('Girls Love'),
('Gourmet'),
('Horror'),
('Josei'),
('Kids'),
('Mystery'),
('Romance'),
('Sci-Fi'),
('Seinen'),
('Shoujo'),
('Shounen'),
('Slice of Life'),
('Sports'),
('Supernatural'),
('Suspense');