INSERT INTO studio_lista (studio_nev) VALUES 
('81 Produce'),
('10Gauge'),
('100studio'),
('7doc'),
('5 Inc.'),
('1IN'),
('3xCube'),
('33 Collective'),
('ADV Films'),
('Aniplex of America'),
('A-1 Pictures'),
('AIC'),
('AQUA ARIS'),
('Ashi Productions'),
('Actas'),
('Asahi Production'),
('Alpha Group'),
('A.C.G.T.'),
('Ai Addiction'),
('AIC ASTA'),
('Artmic'),
('Animation Do'),
('APPP'),
('arma bianca'),
('Alpha Animation'),
('AIC PLUS+'),
('AT-2'),
('Ascendent Animation'),
('Akatsuki'),
('Ascension'),
('AXsiZ'),
('AlphaPolis'),
('Agent 21'),
('AIC Build'),
('Animaruya'),
('ARCUS'),
('ADK Emotions NY Inc.'),
('Acca effe'),
('A-Real'),
('ABC Frontier'),
('Animation Staff Room'),
('AIC Classic'),
('ACC Production'),
('A-Line'),
('Andraft'),
('Arch'),
('Anon Pictures'),
('Anpro'),
('Au Praxinoscope'),
('Atelier Pontdarc'),
('Anima&Co.'),
('AC-Bu'),
('AN Entertainment'),
('ARECT'),
('Anime Friend'),
('AION Studio'),
('Ai Yume Mai'),
('Aiti St.'),
('Alfred Imageworks'),
('Alice Production'),
('Arcturus'),
('An DerCen'),
('ABC Animation Studio'),
('Alke'),
('Anime Tokyo'),
('Aurora Animation'),
('Animation 501'),
('AIC Project'),
('ANiMix Project'),
('Atti Production'),
('Atorie A.B.C.'),
('Amineworks'),
('Amarcord'),
('Aiko'),
('Alpha Pictures'),
('Animation Lab Japan'),
('Ark'),
('Albacrow'),
('ANIDO FILM'),
('Ankama Animations'),
('Aurum Production'),
('Arcs Create'),
('AIC Takarazuka'),
('bilibili'),
('Bandai Entertainment'),
('Bones'),
('Bushiroad'),
('BS Fuji'),
('Bandai Namco Music Live'),
('BS NTV'),
('Blue bread'),
('Bridge'),
('B.CMAY PICTURES'),
('Big Firebird Culture'),
('Bandai Visual USA'),
('Bouncy'),
('BYMENT'),
('Blue Cat'),
('BOMB! CUTE! BOMB!'),
('BS TV Tokyo'),
('Bakken Record'),
('BUG FILMS'),
('Boyan Pictures'),
('B&T'),
('Buemon'),
('Bebow'),
('Bigcat Studio'),
('Big Wing'),
('Bibury Animation CG'),
('Borutong'),
('Bellnox Films'),
('Blaze Studio'),
('Big Pine Animation Studio'),
('Blue Moon Studio Inc.'),
('Blue Note'),
('Benlai Pictures'),
('Brio Animation'),
('Beijing Sunchime Happy Culture Company'),
('Bitgang'),
('Bianyue Culture'),
('Beijing Rocen Digital'),
('Creators in Pack'),
('Crunchyroll SC Anime Fund'),
('C-Station'),
('CCTV Animation Group'),
('Collaboration Works'),
('CHOCOLATE'),
('Craftar Studios'),
('CLAP'),
('Cloud Hearts'),
('CBS Sony Group'),
('Chiptune'),
('Creative Power Entertaining'),
('Coastline Animation Studio'),
('CUCURI'),
('CANON RECORDINGS'),
('cogitoworks'),
('Cafe de Jeilhouse'),
('Creators Dot Com'),
('Children''s Corner'),
('Cocktail Media'),
('Creative House Pocket'),
('CUC Anima'),
('Chongzhuo Animation'),
('CD Projekt Red'),
('Circus Production'),
('Cutie Bee'),
('Circle Tribute'),
('CREi'),
('CinePix'),
('Chenghuang Yinghua'),
('C&S Production'),
('C and R'),
('Concept Films'),
('Chimu Jika Hatsuden'),
('Discotek Media'),
('DLE'),
('David Production'),
('Disney Platform Distribution'),
('DMM.futureworks'),
('Dongwoo A&E'),
('DandeLion Animation Studio'),
('Decovocal'),
('Daewon Media'),
('Dream Entertainment'),
('Dynamo Pictures'),
('Dangun Pictures'),
('DC Impression Vision'),
('DiC Entertainment'),
('Deregula'),
('D.ROCK-ART'),
('Datama Film'),
('Dancing CG Studio'),
('Digital Network Animation'),
('Dazzling Star'),
('drop'),
('Dyna Method'),
('Djinn Power'),
('Diwphalanx Records'),
('Dongyang Animation'),
('Dai-Ichi Douga'),
('D''ART Shtajio'),
('Daysview Animation'),
('Delpic'),
('Days'),
('Drawing and Manual'),
('Dawn Animation'),
('Da Huoniao Donghua'),
('Eiken'),
('Echoes'),
('ENGI'),
('E&G Films'),
('Encourage Films'),
('East Fish Studio'),
('EDGE'),
('Eallin'),
('Enishiya'),
('Emon'),
('Ekura Animal'),
('Elias'),
('EKACHI EPILKA'),
('Egg'),
('Escape Velocity Animation'),
('Enjin Productions'),
('Ezόla'),
('Executive Decision'),
('Eshoya Honpo'),
('evg'),
('Enzo Animation'),
('Ekakiya'),
('Ether Kitten'),
('e-notion'),
('Ezo Kobo'),
('feel.'),
('Fanworks'),
('Flat Studio'),
('Felix Film'),
('Fenz'),
('Fuji Creative'),
('Front Line'),
('Fukushima Gaina'),
('Flying Fish Studio'),
('flag Co.'),
('Fever Creations'),
('Geneon Entertainment USA'),
('Gonzo'),
('Group TAC'),
('Geidai Animation'),
('Gainax'),
('Geneon Universal Entertainment'),
('Gathering'),
('Green Bunny'),
('Graphinica'),
('GANSIS'),
('Geek Toys'),
('Good Smile Film'),
('Gaina'),
('G-angle'),
('Geno Studio'),
('Grouper Productions'),
('G-Lam'),
('Gravity Well'),
('Gift-o’-Animation'),
('GEMBA'),
('GARDEN LODGE'),
('Giga Production'),
('G.P Entertainment'),
('Gainax Kyoto'),
('G&G Direction'),
('Ga-Crew'),
('Guton Animation Studio'),
('GRIZZLY'),
('Ginga Teikoku'),
('Garyuu Studio'),
('Gambit'),
('Green Monster Team'),
('GUMBLAB'),
('Griot Groove'),
('Gunners'),
('Gonzino'),
('GAV Video'),
('Gosay Studio'),
('Grom'),
('Haoliners Animation League'),
('Hoods Entertainment'),
('Happinet Phantom Studios'),
('High Energy Studio'),
('Hifumi'),
('Hayabusa Film'),
('Horgos Coloroom Pictures'),
('Horannabi'),
('Hand to Mouse.'),
('HS Pictures Studio'),
('Husio Studio'),
('HM Heros'),
('Happy Toon'),
('Hu Po Donghua'),
('Hifumi Shobo'),
('happyproject'),
('Honoo'),
('Hei Chao Yinghua'),
('Hai An Xian Donghua Gongzuo Shi'),
('helo.inc'),
('Hanjin Animation'),
('iQIYI'),
('ILCA'),
('Iconix Entertainment'),
('Ijigen Tokyo'),
('Imagica Infos'),
('Imagin'),
('IMAGICA Lab.'),
('I.Gzwei'),
('Imagineer'),
('Image House'),
('Issen'),
('Infinity Vision'),
('iDreamSky'),
('Inugoya'),
('iDRAGONS Creative Studio'),
('Ishimori Entertainment'),
('Imagestone Inc.'),
('Imagica Digitalscape'),
('Ishibashi Planning'),
('IKK Room'),
('Imagica Imageworks'),
('Jumondou'),
('Jumonji'),
('J.T.P.P.'),
('JCF'),
('Joker Films'),
('J.C.F.'),
('Japan Taps'),
('J.K.I'),
('JOF'),
('Jichitai Anime'),
('JJJOY Animation Studios'),
('Kyoto Animation'),
('Kachidoki Studio'),
('KSS'),
('Kamikaze Douga'),
('Kuri Jikken Manga Koubou'),
('Kate Arrow'),
('Kitty Film Mitaka Studio'),
('Kanaban Graphics'),
('Koei'),
('Koinrush Studio'),
('Kyoto Broadcasting System'),
('Konami Cross Media NY'),
('Kung Fu Frog Animation'),
('Korean Academy of Film Arts'),
('Kuaikan Manhua'),
('Konami animation'),
('Kill Time Communication'),
('Kyoto University of the Arts'),
('Kid+Kid Animation Studio'),
('Kitchen Ltd.'),
('Kusama Art'),
('Keica'),
('Kagome Company'),
('KaKa Technology Studio'),
('Kachigarasu'),
('K contents'),
('Kami Kukan'),
('Kyushu Network Animation'),
('Kent House'),
('Kigumi'),
('KKC Animation Production'),
('Kaca Entertainment'),
('Karasfilms'),
('Kinematics'),
('Lune-Pictures'),
('Lerche'),
('Lay-duce'),
('L²Studio'),
('Lapin Track'),
('Light Chaser Animation Studios'),
('Lyrics'),
('Larx Entertainment'),
('Liu Cong Animation'),
('Liyu Culture'),
('Locus Corporation'),
('LX Animation Studio'),
('l-a-unch・BOX'),
('Live2D Creative Studio'),
('Lingsanwu Animation'),
('LB Commerce'),
('Lan Ying Yingshi'),
('Liu Lin Yi Dongman'),
('Lead'),
('LEVELS'),
('Movic'),
('Madhouse'),
('Magic Capsule'),
('Mediabank'),
('MAPPA'),
('Magic Bus'),
('Mushi Production'),
('Maiden Japan'),
('miHoYoAnime'),
('Manglobe'),
('Millepensee'),
('Marvelous AQL'),
('Mirai Film'),
('Maxilla'),
('Marza Animation Planet'),
('Mimoid'),
('Maho Film'),
('Making Animation'),
('Meltdown'),
('Mili Pictures'),
('Minakata Laboratory'),
('Maboroshi Koubou'),
('MediaNet Pictures'),
('monofilmo'),
('Micro House'),
('Mousou Senka'),
('Miota'),
('MB planning'),
('Melissa'),
('Manga Productions'),
('Momoi Planning'),
('MMT Technology'),
('Maro Studio'),
('Magia Doraglier'),
('MASTER LIGHTS'),
('Moss Design Unit'),
('Maru Animation'),
('Multi Access Company'),
('maroyaka'),
('Miki Production'),
('Mikimoto Production'),
('M&M'),
('MoMo Production'),
('Miyuki Production'),
('MI'),
('Magma Studio'),
('Marone'),
('MAT'),
('Mook DLE'),
('Mirai Fusion'),
('Nihon Ad Systems'),
('NHK Enterprises'),
('NuTech Digital'),
('Nagoya Broadcasting Network'),
('NetEase'),
('Nomad'),
('Netflix'),
('NichiNare'),
('New Generation'),
('Niceboat Animation'),
('Nexus'),
('NADA Holdings'),
('Noovo'),
('NHK Art'),
('Netmarble'),
('Natural High'),
('Nippon TV Douga'),
('Nagoya University of Arts and Sciences'),
('NANON CREATIVE'),
('Namu Animation'),
('Neft Film'),
('Nichicaline'),
('NEWON'),
('Nekonigashi Inc.'),
('nobishiro lab'),
('Network Kouenji Studio'),
('Nippon Ramayana Film'),
('Nishiki Studio'),
('Next'),
('OLM'),
('Office TakeOut'),
('Orange'),
('OLM Digital'),
('Oddjob'),
('Onionskin'),
('Office No. 8'),
('Okuruto Noboru'),
('ORADA COMPANY'),
('Office AO'),
('Okumaza'),
('October Media'),
('Onion Studio'),
('Outline'),
('ORCEN'),
('Oyster'),
('ONIRO'),
('OZ'),
('ORENDA'),
('Odolttogi'),
('Office DCI'),
('Original Dream'),
('Production I.G'),
('Polygon Pictures'),
('Project No.9'),
('Pony Canyon Enterprises'),
('Pie in the sky'),
('Picture Magic'),
('Production Reed'),
('PP Project'),
('Peak Hunt'),
('pH Studio'),
('Painting Dream'),
('Pinkfong'),
('Platinum Vision'),
('PRA'),
('Piso Studio'),
('Plum'),
('Palm Studio'),
('Pb Animation'),
('PrimeTime'),
('Pops Inc.'),
('Pmats9 studio'),
('Passion Paint Animation'),
('Project Team Sarah'),
('Pollyanna Graphics'),
('Project Studio Q'),
('P core'),
('Production D.M.H'),
('Paper Plane Animation Studio'),
('Point Pictures'),
('production doA'),
('Planet Cartoon'),
('Polygon Magic'),
('Production Wave'),
('Paper Animation'),
('Pancake'),
('Penta Show Studios'),
('Project Team Muu'),
('Pink Cat'),
('Pak Production'),
('Potato House'),
('Planet Nemo Animation'),
('Poly Animation'),
('Picona'),
('Piko Studio'),
('PoPoCo'),
('Qzil.la'),
('qmotri'),
('Quad'),
('Qingxiang Culture'),
('Qianqi Animation'),
('Qualia Animation'),
('Qiying Animation'),
('Quebico'),
('QualiArts'),
('Radix'),
('RG Animation Studios'),
('Red Dog Culture House'),
('Rising Force'),
('Revoroot'),
('R11R'),
('Ryuu M''s'),
('ROLL2'),
('Rabbit Machine'),
('Ripromo'),
('Raiose'),
('Rhythmos'),
('Reirs'),
('Rock''n Roll Mountain'),
('Ranzai Studio'),
('REALTHING'),
('Reiki Eyes Animation'),
('Rankin/Bass Productions'),
('Sunrise'),
('Shueisha'),
('Studio Deen'),
('Studio Pierrot'),
('Shin-Ei Animation'),
('Studio Mausu'),
('SILVER LINK.'),
('Showgate'),
('Seven'),
('Studio Hibari'),
('Sammy'),
('Studio Comet'),
('Studio 9 Maiami'),
('SANZIGEN'),
('Studio 1st'),
('Studio Ghibli'),
('Sony Pictures Entertainment'),
('Studio Fantasia'),
('Suzuki Mirano'),
('Seven Arcs'),
('Signal.MD'),
('Shirogumi'),
('Streamline Pictures'),
('Studio Eromatick'),
('Science SARU'),
('Studio BAZOOKA'),
('Shuka'),
('Sogo Vision'),
('Studio A-CAT'),
('Saigo no Shudan'),
('Studio Live'),
('Studio Moriken'),
('Studio Hokiboshi'),
('Shengying Animation'),
('Scooter Films'),
('SELFISH'),
('Shion'),
('Studio VOLN'),
('Sola Digital Arts'),
('Studio Placebo'),
('Studio Jemi'),
('Sunrise Beyond'),
('studio MOTHER'),
('SMIRAL Animation'),
('Shimogumi'),
('Studio Blanc.'),
('Studio Rikka'),
('Shenman Entertainment'),
('Studio Crocodile'),
('Silver'),
('Studio Elle'),
('Super Normal Studio'),
('Studio OX'),
('SEK Studios'),
('Studio Chizu'),
('Staple Entertainment'),
('Shindeban Film'),
('Studio RE:Map'),
('Sola Entertainment'),
('Studio Kaab'),
('Stereotype'),
('Shura'),
('Sharefun Studio'),
('Studio Palette'),
('Studio CANDY BOX'),
('Saetta'),
('Shanghai Hippo Animation'),
('Studio M2'),
('Shochiku Animation Institute'),
('Shykeumo Animation Studio'),
('Sunflowers'),
('Stay Luck'),
('Studio Soul'),
('Shinjukuza'),
('Studio Boogie Nights'),
('Studio Kingyoiro'),
('Studio Daisy'),
('Sony Interactive Entertainment'),
('Sublimation'),
('Square Enix Visual Works'),
('Studio Flad'),
('Studio Ponoc'),
('SIDO LIMITED'),
('Studio Bingo'),
('SIGNIF'),
('studio YOG'),
('Studio Ranmaru'),
('Studio Prokion'),
('Sonsan Kikaku'),
('Studio Kafka'),
('Studio Ten Carat'),
('Sugar Boy'),
('Studio LEO'),
('STUDIO 8 DOGS'),
('Studio A. Craft'),
('Studio Easter'),
('Studio Gazelle'),
('Studio Ten'),
('Scarlett'),
('Suspenders'),
('Samsara Animation Studio'),
('Studio March'),
('Studio Core'),
('Stingray'),
('Sprite Animation Studios'),
('Studio NOIX'),
('Studio Bogey'),
('Sunny Gapen'),
('Soigne'),
('Studio Eight Color'),
('Studio Lemon'),
('Sakura Eiga-sha'),
('Sankaku'),
('Square Pictures'),
('Studio Dolphin Night'),
('StarLink'),
('Space-X'),
('Studio Shelter'),
('Studio Ppuri'),
('Studio Mir'),
('Studio UGOKI'),
('Studio AWAKE'),
('Studio Lotus'),
('Studio Izena'),
('studioDOT'),
('Studio Maybe'),
('studio maf'),
('Studio Clutch'),
('Studio Dotou'),
('Studio Harutonari'),
('Skydance'),
('Saber Works'),
('soket'),
('Sasayuri'),
('Studio Add'),
('Studio Fusion'),
('Studio D-Volt'),
('Starlight Entertainment'),
('Studio Himalaya'),
('Shenfan Animation'),
('Studio Cats'),
('Studio B&M'),
('Studio Jin'),
('STUDIO6''oN'),
('Sumomo Film'),
('Studio Gadget'),
('studio hb'),
('Story Effect'),
('SJYNEXCUS'),
('Studio Guts'),
('Studio W.Baba'),
('Studio Hakk'),
('Studio CA'),
('Studio Khronos'),
('Studio Carbuncle'),
('Studio World'),
('Studio Z5'),
('Studio WHO'),
('Toei Animation'),
('TMS Entertainment'),
('TBS'),
('Tencent Video'),
('TOHO'),
('TOHO animation'),
('T-Rex'),
('TNK'),
('Trigger'),
('Triangle Staff'),
('The Answer Studio'),
('Tamabi'),
('Takun Manga Box'),
('Toranoana'),
('Tsuburaya Productions'),
('TCJ'),
('Toshiba EMI'),
('Tokyu Agency'),
('Tsuchida Productions'),
('TOHO animation STUDIO'),
('Transcendence Picture'),
('Trash Studio'),
('Topcraft'),
('TriF Studio'),
('TrioPen Studio'),
('Thundray'),
('Teatro Nishi Tokyo Studio'),
('Tokyo Movie'),
('Tomovies'),
('Takahashi Studio'),
('Team YokkyuFuman'),
('TV Douga'),
('Tokyo Polytechnic University'),
('Tianshi Wenhua'),
('Taikong Works'),
('Tokyo TV Douga'),
('Taomee'),
('TAKI Corporation'),
('team Yamahitsuji'),
('Tengu Kobo'),
('TAP'),
('Tryforce'),
('TthunDer Animation'),
('Tonko House'),
('Tomason'),
('Team OneOne'),
('Tohjak'),
('TANOsim'),
('Tang Cai Zhaopin'),
('The Gate Studio'),
('TanKong Pictures'),
('TypeZero'),
('TV Tokyo Communications'),
('Tsubo Production'),
('Twenty First'),
('TEC'),
('TiMi Studio Group'),
('The Monk Studios'),
('Ten Tails Animation'),
('Team TillDawn'),
('Twilight Studio'),
('Tsukimidou'),
('TOCSIS'),
('ufotable'),
('Ultra Super Pictures'),
('Urban Vision'),
('UWAN Pictures'),
('UKA'),
('Urban Product'),
('Unend'),
('UchuPeople'),
('Voil'),
('Viewworks'),
('Visual Flight'),
('V-sign'),
('Warner Bros. Japan'),
('WAO World'),
('Wonder Cat Animation'),
('W-Toon Studio'),
('WOWMAX'),
('Wright Staff'),
('Windy Studio'),
('Wave Master'),
('Wolf Smoke Studio'),
('Wanda Media'),
('WonderLand'),
('Wang Film Productions'),
('Watanabe Promotion'),
('Winfuture Media'),
('Xing Yi Kai Chen'),
('Xiaoming Taiji'),
('Xanthus Media'),
('Yomiuri TV Enterprise'),
('Youku'),
('Yokohama Animation Laboratory'),
('Yaoyorozu'),
('Yuewen Animation & Comics'),
('YHKT Entertainment'),
('Yi Chen Animation'),
('yell'),
('YURUPPE Inc.'),
('Yoyogi Animation Gakuin'),
('Yinhe Changxing Culture'),
('Y&N Brothers'),
('Yoon''s Color'),
('Yumao Wenhua'),
('York Animation'),
('Youth Film Studio'),
('Yonago Gainax'),
('Yili Animation Studio'),
('Zero-G Room'),
('Ziine Studio'),
('Zhou Ling Wenhua'),
('Zhou Shen Studio'),
('Zoland Animation'),
('ZOOM ENTERPRISE'),
('8bit'),
('717 Animation Studio'),
('Aubeck'),
('Akatsuki Media Studio'),
('Amuse Creative Studio'),
('Atelier Peuplier'),
('Aura Studio'),
('Azuki'),
('BENTEN Film'),
('B.COOL STUDIO'),
('BIGBIGSUN'),
('bushes'),
('dugout'),
('Fantawild Animation'),
('GoHands'),
('Hololive Production'),
('NAZ'),
('Nice Boat Animation'),
('Telescreen'),
('TROYCA'),
('Vasoon Animation'),
('YNUO');
